import React from "react";
import { Download, Filter } from "lucide-react";
import {
  AreaChart,
  Area,
} from "recharts";
import {
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  ResponsiveContainer,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  Legend,
} from "recharts";


import Navbar from '../../Components/Navbar';
import Header from '../../Components/Header';

const vehicleData = [
  { name: "MP04K7008", value: 2.1 },
  { name: "MP42C2682", value: 0.1 },
  { name: "MP04WC6156", value: 2.1 },
  { name: "MP20GB5721", value: 2.1 },
  { name: "MP07GA6085", value: 2.1 },
];

const cameraData = [
  { name: "Distillery 1", value: 7 },
  { name: "Distillery 2", value: 6 },
  { name: "Distillery 3", value: 4 },
  { name: "Distillery 4", value: 3 },
  { name: "Distillery 5", value: 15 },
  { name: "Distillery 6", value: 12 },
];

const rankingData = [
  { name: "Distillery A", value: 190 },
  { name: "Distillery B", value: 170 },
  { name: "Distillery C", value: 120 },
  { name: "Distillery D", value: 110 },
  { name: "Distillery E", value: 108 },
];

const authData = [
  { name: "Unit 1", author: 60, entry: 55, exit: 5 },
  { name: "Unit 2", author: 45, entry: 38, exit: 4 },
  { name: "Unit 3", author: 30, entry: 28, exit: 2 },
  { name: "Unit 4", author: 20, entry: 19, exit: 1 },
];

const pieData = [
  { name: "A", value: 20 },
  { name: "B", value: 15 },
  { name: "C", value: 10 },
  { name: "D", value: 12 },
  { name: "E", value: 18 },
  { name: "F", value: 8 },
  { name: "G", value: 17 },
];

const COLORS = [
  "#60A5FA",
  "#FBBF24",
  "#34D399",
  "#F87171",
  "#A78BFA",
  "#FB7185",
  "#4ADE80",
];

const Card = ({ title, children }) => {
  return (
    <div className="bg-white rounded-2xl shadow-md p-4 w-full overflow-hidden">
      <h2 className="text-lg font-semibold text-gray-700 mb-4">
        {title}
      </h2>

      <div className="w-full h-[300px]">
        {children}
      </div>
    </div>
  );
};

const AnalysisSummary = () => {
  return (

    <>
    <Header/>
    <Navbar/>
    <div className="min-h-screen bg-gray-100 p-4 md:p-6 mt-30">
      
      {/* Heading */}
    {/* Heading + Buttons */}
<div className="flex flex-col md:flex-row md:items-center md:justify-between mb-6 gap-4">
  
  <div>
    <h1 className="text-3xl font-bold text-gray-800">
      Analysis Summary
    </h1>

    <p className="text-gray-500 text-sm">
      Complete Analysis of all Alerts
    </p>
  </div>

  {/* Buttons */}
  <div className="flex gap-3">
    
  {/* Export Button */}
  <button className="flex items-center gap-2 px-4 py-2 bg-white border border-blue-500 text-blue-600 rounded-lg hover:bg-blue-50 transition">
    <Download size={18} />
    Export
  </button>

  {/* Filter Button */}
  <button className="flex items-center gap-2 px-4 py-2 bg-white border border-red-400 text-red-500 rounded-lg hover:bg-red-50 transition">
    <Filter size={18} />
    Filter
  </button>

  </div>
</div>

      

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        {/* Vehicle Delay */}
        <Card title="Vehicle Delay by Vehicle Number">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart
              data={vehicleData}
              layout="vertical"
              margin={{ left: 20 }}
            >
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis type="number" />
              <YAxis dataKey="name" type="category" />
              <Tooltip />

              <Bar
                dataKey="value"
                fill="#60A5FA"
                radius={[0, 10, 10, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        </Card>

        {/* Camera Down */}
        <Card title="Camera Down by Distillery">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={cameraData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />

              <Bar
                dataKey="value"
                fill="#FBBF24"
                radius={[10, 10, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        </Card>

        {/* Pie Chart */}
        <Card title="Alerts Generated by Distilleries">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={pieData}
                dataKey="value"
                outerRadius={110}
                label
              >
                {pieData.map((entry, index) => (
                  <Cell
                    key={index}
                    fill={COLORS[index % COLORS.length]}
                  />
                ))}
              </Pie>

              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        </Card>

        {/* Ranking */}
        <Card title="Distillery Alerts Ranking">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={rankingData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />

              <Bar
                dataKey="value"
                fill="#4ADE80"
                radius={[10, 10, 0, 0]}
              />
            </BarChart>
          </ResponsiveContainer>
        </Card>

        {/* Authorized */}
        <Card title="Authorised Entry/Exit by Distillery ANPR">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={authData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Legend />

              <Bar dataKey="author" fill="#4ADE80" />
              <Bar dataKey="entry" fill="#60A5FA" />
              <Bar dataKey="exit" fill="#F87171" />
            </BarChart>
          </ResponsiveContainer>
        </Card>

        {/* Unauthorized */}
        <Card title="Unauthorised Entry/Exit by Distillery ANPR">
          <div className="flex items-center justify-center h-full text-gray-400 text-lg">
            No Data Available
          </div>
        </Card>

      </div>
    </div>
    </>
  );
};

export default AnalysisSummary;