export const vendorRecords = [
  {
    id: 1,
    serviceType: "gps",
    vendorName: "Intugine Technologies",
    contact: "9986663220",
    email: "prakharverma@intugine.com",
    address: "Bengaluru, Karnataka 560034",
    active: true,
  },
  {
    id: 2,
    serviceType: "gps",
    vendorName: "VKGPS Tracker",
    contact: "8109784355",
    email: "admin@vkgpstracker.com",
    address: "21/1 RamKrishna Bagh Indore",
    active: true,
  },
  {
    id: 3,
    serviceType: "gps",
    vendorName: "Autoplant Systems India Pvt. Ltd",
    contact: "9953819495",
    email: "harsh.raghav@autoplant.in",
    address: "N/A",
    active: true,
  },
  {
    id: 4,
    serviceType: "gps",
    vendorName: "SRAG_INDIA_GPS",
    contact: "N/A",
    email: "rahul@trackobit.com",
    address: "Rajasthan",
    active: true,
  },
  {
    id: 5,
    serviceType: "elock",
    vendorName: "Binary Semantics Limited",
    contact: "8168322614",
    email: "rahul.sharma2@binarysemantics.com",
    address: "38, Electronic City, Sector 18, Gurugram-122015, Haryana",
    active: true,
  },
  {
    id: 6,
    serviceType: "elock",
    vendorName: "IMZ Corporate Private Limited",
    contact: "9311342666",
    email: "Raman.sharma@imzcorporate.com",
    address: "New Delhi",
    active: true,
  },
  {
    id: 7,
    serviceType: "gps",
    vendorName: "Roadcast Tech Solutions Pvt. Ltd.",
    contact: "9810647603",
    email: "kajal.agrawal@roadcast.in",
    address:
      "B-66, Naraina Industrial Area Phase II, Second Floor New Delhi – 110028",
    active: true,
  },
  {
    id: 8,
    serviceType: "gps",
    vendorName: "QTS SOLUTIONS PVT LTD",
    contact: "8750597777",
    email: "smajumdar@qtssolutions.com",
    address: "N/A",
    active: true,
  },
];